-- https://www.hackerrank.com/challenges/contest-leaderboard/problem

SELECT HACKER_ID, NAME, SUM(MAX_SCORE) AS TOTAL_SCORE
FROM(
    SELECT H.HACKER_ID, NAME, CHALLENGE_ID, MAX(SCORE) AS MAX_SCORE
    FROM HACKERS H JOIN SUBMISSIONS S ON H.HACKER_ID=S.HACKER_ID
    GROUP BY H.HACKER_ID, NAME, CHALLENGE_ID
) TEMP
GROUP BY HACKER_ID, NAME
HAVING TOTAL_SCORE>0
ORDER BY TOTAL_SCORE DESC, HACKER_ID

-- github.com/ArutselvanManivannan
