-- https://www.hackerrank.com/challenges/full-score/problem

SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
JOIN SUBMISSIONS S
ON H.HACKER_ID=S.HACKER_ID
JOIN CHALLENGES C
ON C.CHALLENGE_ID=S.CHALLENGE_ID
JOIN DIFFICULTY D
ON D.DIFFICULTY_LEVEL=C.DIFFICULTY_LEVEL
WHERE D.SCORE=S.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(S.SUBMISSION_ID) > 1
ORDER BY COUNT(S.SUBMISSION_ID) DESC, H.HACKER_ID


-- github.com/ArutselvanManivannan
