SELECT C.CONTEST_ID, C.HACKER_ID, C.NAME, SUM(TOTAL_SUBMISSIONS) AS TS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TAS, SUM(TOTAL_VIEWS) AS TV, SUM(TOTAL_UNIQUE_VIEWS) AS TUV
FROM (
    CONTESTS C
    JOIN COLLEGES CLG
    ON C.CONTEST_ID=CLG.CONTEST_ID
    JOIN CHALLENGES CH
    ON CH.COLLEGE_ID=CLG.COLLEGE_ID
    LEFT JOIN(
        SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
        FROM VIEW_STATS
        GROUP BY CHALLENGE_ID
    )VS
    ON VS.CHALLENGE_ID=CH.CHALLENGE_ID
    LEFT JOIN(
        SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
        FROM SUBMISSION_STATS
        GROUP BY CHALLENGE_ID
    ) SS
    ON SS.CHALLENGE_ID=CH.CHALLENGE_ID
)
GROUP BY C.CONTEST_ID, C.HACKER_ID, C.NAME
HAVING TS>0 OR TAS>0 OR TV>0 OR TUV>0
ORDER BY C.CONTEST_ID


-- github.com/ArutselvanManivannan
